services:
  - type: web
    name: atlas
    env: python
    headers:
      - path: /*
        name: [user]-Policy
        value: "microphone=*, camera=*"
      - path: /*
        name: [user]-Policy
        value: "microphone *; camera *"